### ISSUE TITLE
clear problem definition and goal

### ISSUE THREAD

**Issue by sashafirsov** [besworks/widget-injector#1]
It is unclear what use cases the widget-injector meant to resolve. 
In my project I am facing the similar issues with currentScript undefined and curious what are the use cases difference?
In my case the purpose of currentScript use is to find closest shadow root and search for sub-components there. Kind of replacement of document.querySelector() which of course does not work inside of shadowRoot.

**Comment by besworks** [comment]
I think this project will help you. I've worked around the currentScript == null issue for a similar purpose. I needed to select elements contained inside a ShadowRoot from a script which is also inside the ShadowRoot.

If I'm not mistaken, this is your issue:

`

  <div id="myElement"></div>
  <script>
    document.querySelector('#myElement'); // returns undefined
  </script>

`

Using my widget injector:

`

  <div id="myElement"></div>
  <script>
    Widget('my-widget-type', widget => {
      widget.shadowRoot.querySelector('#myElement'); // returns the element!
    });
  </script>

`

The script tag widget injection is really secondary to this purpose. The important part for you would be the bubbling event set up by the WidgetLoader / Widget function combo in `widget-framework.js`.

**Comment by besworks** [comment]
I added a barebones example that excludes the injector logic.

- [script](https://github.com/besworks/widget-injector/blob/master/widget-barebones.js)
- [test](https://github.com/besworks/widget-injector/blob/master/widget-barebones-test.html)
